<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SearchFunctionSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5cc7b126-4243-4932-8790-79b29666a1e4</testSuiteGuid>
   <testCaseLink>
      <guid>2b507d2e-d736-4d26-bf44-5f115609f1af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/search_function/TC_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aafebd9-d6e5-40fa-a282-826fd8a8a512</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce3802ee-1dd5-4cd6-a394-73057b01567e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/search_function/TC_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d80779-79da-49f7-a72f-7a47fc5b94cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb240a4-1a44-4b7e-82e1-a0dc8226d4a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5f3e7de-70ff-47b9-bc75-b46ed3b13407</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/search_function/TC_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9a35b40-7666-4d54-afc7-8acfa4b46eb9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a083157-0afa-432c-bd7a-0e011c223b72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/search_function/TC_04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443d4a0c-181d-4986-8880-5f3160d587f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
